import type { Animal, Shelter } from './types';

export const shelters: Shelter[] = [
  {
    id: 'shelter-1',
    name: 'Abrigo Patas Amigas',
    address: 'Rua do Meio, 123, Cidade Feliz, ES',
    phone: '(27) 99999-1111',
    email: 'contato@patasamigas.org',
    website: 'www.patasamigas.org',
  },
  {
    id: 'shelter-2',
    name: 'Recanto dos Focinhos',
    address: 'Avenida Principal, 456, Vila dos Bichos, ES',
    phone: '(27) 99999-2222',
    email: 'adocao@recantodosfocinhos.com',
    website: 'www.recantodosfocinhos.com',
  },
];

export const animals: Animal[] = [
  {
    id: 'animal-1',
    name: 'Biscoito',
    species: 'Cachorro',
    breed: 'Vira-lata',
    age: 2,
    size: 'Médio',
    gender: 'Macho',
    description: 'Biscoito é um cão super enérgico e brincalhão. Adora correr no parque e buscar bolinhas. Se dá bem com crianças e outros cachorros.',
    story: 'Foi encontrado vagando perto de um parque, muito magro e assustado. Agora está saudável e pronto para um novo começo.',
    personality: ['Brincalhão', 'Energético', 'Amigável', 'Inteligente'],
    health: ['Vacinado', 'Vermifugado', 'Castrado'],
    photos: ['dog-1', 'dog-4'],
    shelterId: 'shelter-1',
  },
  {
    id: 'animal-2',
    name: 'Princesa',
    species: 'Gato',
    breed: 'Siamês',
    age: 4,
    size: 'Pequeno',
    gender: 'Fêmea',
    description: 'Princesa é uma gata calma e carinhosa. Gosta de um bom colo e de longas sonecas ao sol. É um pouco tímida no começo, mas logo se solta.',
    story: 'Sua antiga dona era uma senhora idosa que não podia mais cuidar dela. Está acostumada com ambientes internos e tranquilos.',
    personality: ['Calma', 'Carinhosa', 'Tímida', 'Companheira'],
    health: ['Vacinada', 'Vermifugada', 'Castrada'],
    photos: ['cat-1', 'cat-3'],
    shelterId: 'shelter-2',
  },
  {
    id: 'animal-3',
    name: 'Trovão',
    species: 'Cachorro',
    breed: 'Bulldog',
    age: 7,
    size: 'Médio',
    gender: 'Macho',
    description: 'Apesar do nome, Trovão é um doce de cachorro. Um pouco teimoso, mas muito leal. Gosta de caminhadas curtas e muitos petiscos.',
    story: 'Sua família se mudou para o exterior e não pôde levá-lo. Ele sente falta de ter um lar e um sofá para chamar de seu.',
    personality: ['Leal', 'Teimoso', 'Preguiçoso', 'Amoroso'],
    health: ['Vacinado', 'Vermifugado', 'Castrado', 'Requer cuidados especiais com a pele'],
    photos: ['dog-3'],
    shelterId: 'shelter-1',
  },
  {
    id: 'animal-4',
    name: 'Fagulha',
    species: 'Gato',
    breed: 'Vira-lata',
    age: 1,
    size: 'Pequeno',
    gender: 'Fêmea',
    description: 'Fagulha é uma gatinha cheia de energia. Adora explorar cada canto da casa e brincar com qualquer coisa que se mova. Muito curiosa.',
    story: 'Nasceu na rua e foi resgatada junto com seus irmãos. É a mais aventureira da ninhada.',
    personality: ['Curiosa', 'Energética', 'Independente', 'Esperta'],
    health: ['Vacinada', 'Vermifugada', 'Castrada'],
    photos: ['cat-2', 'cat-4'],
    shelterId: 'shelter-2',
  },
  {
    id: 'animal-5',
    name: 'Pompom',
    species: 'Coelho',
    breed: 'Lionhead',
    age: 1,
    size: 'Pequeno',
    gender: 'Fêmea',
    description: 'Pompom é uma coelha dócil e fofinha. Gosta de cenouras e de ter um espaço seguro para pular. Se assusta com barulhos altos.',
    story: 'Foi comprada por impulso e abandonada quando a família percebeu que coelhos dão trabalho. Procura um lar paciente e amoroso.',
    personality: ['Dócil', 'Calma', 'Assustada'],
    health: ['Saudável', 'Castrada'],
    photos: ['rabbit-1'],
    shelterId: 'shelter-1',
  },
];
